const PUT_TO_TRAY = 'PUT_TO_TRAY';
const ADD_INTERCEPT_URL = 'ADD_INTERCEPT_URL';
const ADD_INTERCEPT_URL_STATUS = 'ADD_INTERCEPT_URL_STATUS';

module.exports = {
  PUT_TO_TRAY,
  ADD_INTERCEPT_URL,
  ADD_INTERCEPT_URL_STATUS
}
